networks:
  auth:

services:
  db:
    image: mysql:8.0-bookworm
    container_name: mysql-db
    env_file: .env
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - auth
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]  
      interval: 30s  
      timeout: 10s
      retries: 3
      start_period: 80s
    restart: always

  migrate:
    image: migrate/migrate:latest
    container_name: migrate-db
    volumes:
      - ../backend/auth/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database",
      "mysql://${DB_USER}:${DB_PASSWORD}@tcp(db:3306)/${DB_NAME}?multiStatements=true&parseTime=true&tls=${DB_TLS}",
      "up"
    ]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - auth
    restart: on-failure:5 

  auth:
    build:
      context: ../
      dockerfile: docker/Dockerfile.auth.dev
    image: accounting-auth
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db: 
        condition: service_healthy
      migrate: 
        condition: service_completed_successfully
    networks:
      - auth
  
  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.front.dev
    image: accounting-front
    ports:
      - "5173:5173"

volumes:
  mysql-data:
