networks:
  accounter:

services:
  db:
    image: mysql:8.0-bookworm
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - accounter
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 80s
    restart: always

  migrate:
    image: migrate/migrate:latest
    container_name: migrate-db
    volumes:
      - ../backend/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database",
      "mysql://${DB_USER}:${DB_PASSWORD}@tcp(db:3306)/${DB_NAME}?multiStatements=true&parseTime=true&tls=${DB_TLS}",
      "up"
    ]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - accounter
    restart: on-failure:5

  backend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.back.prod
    image: accounter
    env_file: ../.env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - accounter
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.front.dev
    image: accounting-front
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - accounter

volumes:
  mysql-data:
