services:
  db:
    image: mysql:8.0-bookworm
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - accounter
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 80s
    restart: always

  migrate:
    image: migrate/migrate:latest
    container_name: migrate-db
    volumes:
      - ./backend/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database",
      "mysql://${DB_USER}:${DB_PASSWORD}@tcp(db:3306)/${DB_NAME}?multiStatements=true&parseTime=true&tls=${DB_TLS}",
      "up"
    ]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - accounter
    restart: on-failure:5

networks:
  accounter:

volumes:
  mysql-data:
